"""describe your changes

Revision ID: f7aca25e51ac
Revises: 
Create Date: 2024-09-22 11:50:40.743037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7aca25e51ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kofi_transactions_message_id', table_name='kofi_transactions')
    op.drop_index('ix_kofi_transactions_verification_token', table_name='kofi_transactions')
    op.drop_table('kofi_transactions')
    op.drop_index('ix_kofi_users_verification_token', table_name='kofi_users')
    op.drop_table('kofi_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kofi_users',
    sa.Column('verification_token', sa.VARCHAR(), nullable=False),
    sa.Column('data_retention_days', sa.INTEGER(), nullable=False),
    sa.Column('latest_request_at', sa.VARCHAR(), nullable=False),
    sa.Column('prefered_currency', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('verification_token')
    )
    op.create_index('ix_kofi_users_verification_token', 'kofi_users', ['verification_token'], unique=False)
    op.create_table('kofi_transactions',
    sa.Column('verification_token', sa.VARCHAR(), nullable=False),
    sa.Column('message_id', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), nullable=False),
    sa.Column('from_name', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=False),
    sa.Column('is_subscription_payment', sa.BOOLEAN(), nullable=False),
    sa.Column('is_first_subscription_payment', sa.BOOLEAN(), nullable=False),
    sa.Column('kofi_transaction_id', sa.VARCHAR(), nullable=False),
    sa.Column('shop_items', sa.BLOB(), nullable=True),
    sa.Column('tier_name', sa.VARCHAR(), nullable=True),
    sa.Column('shipping', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_kofi_transactions_verification_token', 'kofi_transactions', ['verification_token'], unique=False)
    op.create_index('ix_kofi_transactions_message_id', 'kofi_transactions', ['message_id'], unique=False)
    # ### end Alembic commands ###
